"""DIIWES optimizer.

Design choices kept explicit:
  - rank-shaped fitness is used only for the ES gradient;
  - Stein curvature uses raw return units by default;
  - standardized curvature fitness remains available for compatibility checks;
  - no-center curvature uses a leave-one-out pair baseline;
  - curvature EMA is bias-corrected before forming the step denominator;
  - trust-radius clipping is part of the DIIWES update;
  - global, block, directional, and normalized curvature variants are
    available for low-variance Hessian debugging.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Sequence

import numpy as np

from .standard_es import StandardES, centered_ranks


def _vector_correlation(left: np.ndarray, right: np.ndarray) -> float | None:
    """Return a finite Pearson correlation, or None for degenerate vectors."""
    x = np.asarray(left, dtype=np.float64)
    y = np.asarray(right, dtype=np.float64)
    if x.shape != y.shape or x.size < 2:
        return None
    x_centered = x - np.mean(x)
    y_centered = y - np.mean(y)
    denominator = float(np.linalg.norm(x_centered) * np.linalg.norm(y_centered))
    if denominator <= 1e-30 or not np.isfinite(denominator):
        return None
    value = float(np.dot(x_centered, y_centered) / denominator)
    return value if np.isfinite(value) else None


@dataclass
class BufferEntry:
    """A replay-buffer sample generated by a previous search distribution."""

    w: np.ndarray   # The actual parameter vector that was evaluated
    behavior_mu: np.ndarray   # The center parameter from which that sample was originally generated
    sigma: float     # The noise standard deviation used when generating that sample
    dist_old_sq: float # Squared Euclidean distance from behavior_mu in parameter space: ||w - behavior_mu||^2

    fitness: float
    iteration: int


class DIIWES(StandardES):
    """Semi-implicit ES with rank gradients and raw-return Stein curvature."""

    def __init__(
        self,
        num_params: int,
        population_size: int = 200,
        learning_rate: float = 0.02,
        noise_std: float = 0.02,
        l2_coeff: float = 0.0,
        buffer_size: int = 1024,
        reuse_fraction: float = 0.2,
        min_importance_weight: float = 1e-3,
        max_importance_weight: float = 10.0,
        implicit_damping: float = 0.1,
        antithetic: bool = True,
        rank_fitness: bool = True,
        max_grad_norm: float = 0.0,      # What is max_grad_norm? 
        max_sample_age: int = 3,
        buffer_sampling: str = "random",
        elite_quantile: float = 0.25,
        max_param_norm: float | None = None, # What is max_param_norm?
        seed: int | None = None,
        *,
        use_curvature: bool = True,
        curvature_fitness: str = "raw",
        curvature_mode: str = "diag",
        curvature_step_mode: str = "dampen",
        curvature_beta: float = 0.99,    # What is the meaning of curvature_beta? 
        curvature_clip: float = 1e3,
        min_step_multiplier: float = 0.05,  # What is the meaning of min_step_multiplier
        trust_radius: float | None = None,  # What is the meaning of trust_radius?
        ess_min_ratio: float = 0.2,         # What is ess_min ratio? 
        block_slices: Sequence[slice | Sequence[int]] | None = None,
        use_leave_one_out_curvature_baseline: bool = True,
        bias_correct_curvature_ema: bool = True,        # Why ema correct the bias?
    ) -> None:
        super().__init__(
            num_params=num_params,
            population_size=population_size,
            learning_rate=learning_rate,
            noise_std=noise_std,
            l2_coeff=l2_coeff,
            antithetic=antithetic,
            rank_fitness=rank_fitness,
            max_grad_norm=max_grad_norm,
            max_param_norm=max_param_norm,
            seed=seed,
        )
        if not (0.0 <= reuse_fraction <= 1.0):
            raise ValueError("reuse_fraction must be in [0, 1]")
        if min_importance_weight <= 0.0 or max_importance_weight <= 0.0:
            raise ValueError("importance weight bounds must be positive")
        if min_importance_weight > max_importance_weight:
            raise ValueError("min_importance_weight must be <= max_importance_weight")
        if not (0.0 <= curvature_beta < 1.0):
            raise ValueError("curvature_beta must be in [0, 1)")
        if not (0.0 <= min_step_multiplier <= 1.0):
            raise ValueError("min_step_multiplier must be in [0, 1]")
        if trust_radius is not None and trust_radius <= 0.0:
            raise ValueError("trust_radius must be positive when provided")
        if not (0.0 <= ess_min_ratio <= 1.0):
            raise ValueError("ess_min_ratio must be in [0, 1]")

        curvature_fitness = str(curvature_fitness).lower()
        if curvature_fitness not in {"raw", "standardized"}:
            raise ValueError("curvature_fitness must be one of raw, standardized")
        curvature_mode = str(curvature_mode).lower()
        if curvature_mode not in {"global", "block", "diag", "directional"}:
            raise ValueError("curvature_mode must be one of global, block, diag, directional")
        curvature_step_mode = str(curvature_step_mode).lower()
        if curvature_step_mode not in {"dampen", "normalized"}:
            raise ValueError("curvature_step_mode must be one of dampen, normalized")

        self.buffer_size = int(buffer_size)
        self.reuse_fraction = float(reuse_fraction)
        self.min_importance_weight = float(min_importance_weight)
        self.max_importance_weight = float(max_importance_weight)
        self.implicit_damping = float(implicit_damping)
        self.max_sample_age = int(max_sample_age)
        self.buffer_sampling = str(buffer_sampling).lower()
        self.elite_quantile = float(elite_quantile) #What is the meaning of elite_quantile
        self.use_curvature = bool(use_curvature)
        self.curvature_fitness = curvature_fitness
        self.curvature_mode = curvature_mode
        self.curvature_step_mode = curvature_step_mode
        self.curvature_beta = float(curvature_beta)
        self.curvature_clip = float(curvature_clip)
        self.min_step_multiplier = float(min_step_multiplier)
        self.trust_radius = None if trust_radius is None else float(trust_radius)
        self.ess_min_ratio = float(ess_min_ratio)
        self.use_leave_one_out_curvature_baseline = bool(use_leave_one_out_curvature_baseline)
        self.bias_correct_curvature_ema = bool(bias_correct_curvature_ema)
        self.block_slices = self._normalize_block_slices(block_slices)

        self._log_rmin = float(np.log(self.min_importance_weight))
        self._log_rmax = float(np.log(self.max_importance_weight))
        self.sample_buffer: list[BufferEntry] = []
        self.n_reuse_target = int(np.floor(self.population_size * self.reuse_fraction))
        self.hessian_ema = np.zeros(self.num_params, dtype=np.float64)
        self.hessian_ema_count = 0
        self._last_curvature_baseline_mode = "none"
        self._previous_diag_h_raw: np.ndarray | None = None
        self._last_h_split_correlation: float | None = None
        self._last_h_split_sign_agreement: float | None = None
        self._last_h_split_relative_disagreement: float | None = None
        self._last_h_temporal_correlation: float | None = None
        self._last_h_temporal_sign_agreement: float | None = None
        self._last_hessian_for_step_vector: np.ndarray | None = None
        self._last_step_multiplier_vector: np.ndarray | None = None

    @property
    def hessian_for_step_vector(self) -> np.ndarray | None:
        """Return a read-only copy of the signed Hessian used by the last step."""
        if self._last_hessian_for_step_vector is None:
            return None
        value = self._last_hessian_for_step_vector.copy()
        value.setflags(write=False)
        return value

    @property
    def step_multiplier_vector(self) -> np.ndarray | None:
        """Return a read-only copy of the final multiplier used by the last step."""
        if self._last_step_multiplier_vector is None:
            return None
        value = self._last_step_multiplier_vector.copy()
        value.setflags(write=False)
        return value

    def _normalize_block_slices(
        self,
        # It can be None, a sequence of slice objects or a sequence of two-integer sequences of [start,stop] pairs. 
        block_slices: Sequence[slice | Sequence[int]] | None,
    ) -> list[slice]:
        if block_slices is None:
            return [slice(0, self.num_params)]

        normalized: list[slice] = []
        # coverage checks the coverage of the parameters
        coverage = np.zeros(self.num_params, dtype=np.int8)
        for item in block_slices:
            if isinstance(item, slice):
                start = 0 if item.start is None else int(item.start)
                stop = self.num_params if item.stop is None else int(item.stop)
            else:
                if len(item) != 2:
                    raise ValueError("block_slices entries must be slices or [start, stop] pairs")
                start, stop = int(item[0]), int(item[1])
            if start < 0 or stop > self.num_params or start >= stop:
                raise ValueError(f"invalid block slice [{start}, {stop}) for d={self.num_params}")
            coverage[start:stop] += 1
            normalized.append(slice(start, stop))

        if np.any(coverage != 1):
            raise ValueError("block_slices must form a non-overlapping full partition")
        return normalized
    # This part excludes the samples that are too old
    def _valid_buffer_indices(self) -> list[int]:
        return [
            i
            for i, entry in enumerate(self.sample_buffer)
            if self.iteration - entry.iteration <= self.max_sample_age
        ]

    def _select_from_buffer(self, theta_current: np.ndarray, n_select: int) -> list[int]:
        # Gets the indices of buffer samples that are still allowed to be reused.
        valid = self._valid_buffer_indices()
        if n_select <= 0 or not valid:
            return []
        n_select = min(int(n_select), len(valid))

        if self.buffer_sampling == "random":
            return self.rng.choice(valid, size=n_select, replace=False).tolist()

        distances = np.asarray(
            [np.sum((self.sample_buffer[idx].w - theta_current) ** 2) for idx in valid],
            dtype=np.float64,
        )
        if self.buffer_sampling == "distance":
            order = np.argsort(distances)
            return [valid[i] for i in order[:n_select]]

        # First select high-fitness samples, then among those choose nearby ones.
        if self.buffer_sampling == "elite_distance":
            fitness = np.asarray([self.sample_buffer[idx].fitness for idx in valid], dtype=np.float64)
            quantile = np.clip(self.elite_quantile, 0.0, 1.0)
            threshold = np.quantile(fitness, 1.0 - quantile) if quantile > 0.0 else np.inf
            elite_local = np.where(fitness >= threshold)[0]
            if len(elite_local) == 0:
                elite_local = np.arange(len(valid))
            elite_order = elite_local[np.argsort(distances[elite_local])]
            return [valid[i] for i in elite_order[:n_select]]

        raise ValueError(f"unknown buffer_sampling mode: {self.buffer_sampling}")

    def _add_fresh_to_buffer(self, theta_center: np.ndarray, noise: np.ndarray, fitness: np.ndarray) -> None:
        if len(noise) == 0 or self.buffer_size <= 0:
            return
        sigma = float(self.noise_std)
        dist_old_sq = (sigma * sigma) * np.sum(noise * noise, axis=1)
        for i in range(len(noise)):
            self.sample_buffer.append(
                BufferEntry(
                    w=(theta_center + sigma * noise[i]).astype(np.float64, copy=True),
                    behavior_mu=theta_center.astype(np.float64, copy=True),
                    sigma=sigma,
                    dist_old_sq=float(dist_old_sq[i]),
                    fitness=float(fitness[i]),
                    iteration=int(self.iteration),
                )
            )
            if len(self.sample_buffer) > self.buffer_size:
                self.sample_buffer.pop(0)
    # samples are generated in the form that the first half of them is all positive and the second half is all negative.
    def _sample_fresh_noise_with_pairs(
        self,
        n_samples: int,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        if n_samples <= 0:
            empty_noise = np.empty((0, self.num_params), dtype=np.float64)
            empty_idx = np.asarray([], dtype=int)
            return empty_noise, empty_idx, empty_idx

        if not self.antithetic or n_samples == 1:
            return self.rng.randn(n_samples, self.num_params), np.asarray([], dtype=int), np.asarray([], dtype=int)

        half = n_samples // 2
        noise_half = self.rng.randn(half, self.num_params)
        noise = np.concatenate([noise_half, -noise_half], axis=0)
        plus = np.arange(half, dtype=int)
        minus = np.arange(half, 2 * half, dtype=int)
        if n_samples % 2 == 1:
            noise = np.concatenate([noise, self.rng.randn(1, self.num_params)], axis=0)
        return noise.astype(np.float64, copy=False), plus, minus

    def ask(self) -> tuple[np.ndarray, dict[str, Any]]:
        selected = self._select_from_buffer(self.current_params, self.n_reuse_target)

        noise_reused = []
        fitness_reused = []
        sigma_old = []
        dist_old_sq = []
        behavior_mu = []
        for idx in selected:
            entry = self.sample_buffer[idx]
            # The following line converts the old evaluated parameter into a noise relative to the current center
            noise_reused.append((entry.w.astype(np.float64) - self.current_params) / self.noise_std)
            fitness_reused.append(entry.fitness)
            sigma_old.append(entry.sigma)
            # dist_old_sq is the squared parameter-space distance between the evaluated sample w and the old distribution center that generated it.
            dist_old_sq.append(entry.dist_old_sq)
            # behavior_mu is the old center parameter that generated the sample
            behavior_mu.append(entry.behavior_mu)

        n_reused = len(noise_reused)
        n_fresh_needed = self.population_size - n_reused
        noise_fresh, plus_local, minus_local = self._sample_fresh_noise_with_pairs(n_fresh_needed)

        if n_reused:
            # axis = 0 means stacking arrays along the first dimension.
            noise_all = np.concatenate([np.asarray(noise_reused, dtype=np.float64), noise_fresh], axis=0)
            is_reused = np.concatenate(
                [np.ones(n_reused, dtype=bool), np.zeros(len(noise_fresh), dtype=bool)],
                axis=0,
            )
        else:
            noise_all = noise_fresh
            is_reused = np.zeros(len(noise_fresh), dtype=bool)

        fresh_offset = n_reused
        return noise_all, {
            "ask_params": self.current_params.copy(),
            "n_fresh": int(len(noise_fresh)),
            "n_reused": int(n_reused),
            "is_reused": is_reused,
            "buffer_fitness": np.asarray(fitness_reused, dtype=np.float64) if n_reused else None,
            "buffer_sigma_old": np.asarray(sigma_old, dtype=np.float64) if n_reused else None,
            "buffer_dist_old_sq": np.asarray(dist_old_sq, dtype=np.float64) if n_reused else None,
            "buffer_behavior_mu": np.asarray(behavior_mu, dtype=np.float64) if n_reused else None,
            "selected_indices": selected,
            "fresh_pair_plus": fresh_offset + plus_local,
            "fresh_pair_minus": fresh_offset + minus_local,
        }
    # ask_info is the dictionary returned by ask(). It contains metadata needed to reconstruct the full batch. 
    def _compose_full_fitness(
        self,
        fitness: np.ndarray,
        is_reused: np.ndarray,
        ask_info: dict[str, Any] | None,
        batch_size: int,
    ) -> np.ndarray:
        fit = np.asarray(fitness, dtype=np.float64)
        n_reused = int(np.sum(is_reused))
        n_fresh = int(batch_size - n_reused)
        if len(fit) == batch_size:
            full = fit.copy()
            if n_reused and ask_info is not None and ask_info.get("buffer_fitness") is not None:
                full[is_reused] = np.asarray(ask_info["buffer_fitness"], dtype=np.float64)
            return full
        if len(fit) == n_fresh:
            if n_reused and (ask_info is None or ask_info.get("buffer_fitness") is None):
                raise ValueError("fresh-only fitness was provided but buffer_fitness is missing")
            full = np.empty(batch_size, dtype=np.float64)
            full[~is_reused] = fit
            if n_reused:
                full[is_reused] = np.asarray(ask_info["buffer_fitness"], dtype=np.float64)
            return full
        raise ValueError(f"fitness length must be {batch_size} or {n_fresh}, got {len(fit)}")
    # The following code is used to estimate the curvature. 
    # center_f_for_curv is the center fitness on the same scale used for curvature.
    # Check the outliers of the fitness value and the normalized fitness value, particularly for the reused samples.
    def _estimate_fresh_curvature(
        self,
        noise: np.ndarray,
        f: np.ndarray,
        ask_info: dict[str, Any] | None,
        sigma: float,
        center_f_for_curv: float | None = None,
        direction: np.ndarray | None = None,
    ) -> tuple[np.ndarray | None, int]:
        self._last_h_split_correlation = None
        self._last_h_split_sign_agreement = None
        self._last_h_split_relative_disagreement = None
        self._last_h_temporal_correlation = None
        self._last_h_temporal_sign_agreement = None
        if ask_info is None:
            return None, 0
        plus = np.asarray(ask_info.get("fresh_pair_plus", []), dtype=int)
        minus = np.asarray(ask_info.get("fresh_pair_minus", []), dtype=int)
        if len(plus) == 0 or len(minus) == 0:
            return None, 0

        n_pairs = min(len(plus), len(minus))
        plus = plus[:n_pairs]
        minus = minus[:n_pairs]
        eps = np.asarray(noise[plus], dtype=np.float64)
        s_pair = np.asarray(f[plus] + f[minus], dtype=np.float64)

        if center_f_for_curv is not None:
            pair_signal = s_pair - 2.0 * float(center_f_for_curv)
            baseline_mode = "center"
        elif self.use_leave_one_out_curvature_baseline and n_pairs > 1:
            loo_mean = (float(np.sum(s_pair)) - s_pair) / float(n_pairs - 1)
            pair_signal = s_pair - loo_mean
            baseline_mode = "leave_one_out"
        elif self.use_leave_one_out_curvature_baseline:
            pair_signal = s_pair
            baseline_mode = "single_pair_zero_baseline"
        else:
            baseline = float(0.5 * np.mean(s_pair))
            pair_signal = s_pair - 2.0 * baseline
            baseline_mode = "same_sample_mean"
        self._last_curvature_baseline_mode = baseline_mode

        sigma_sq = float(sigma) * float(sigma)
        if self.curvature_mode == "diag":
            scale = 2.0 * sigma_sq + 1e-12
            pair_moments = pair_signal[:, None] * (eps * eps - 1.0)
            h_raw = np.mean(pair_moments, axis=0) / scale
            h_raw = h_raw.astype(np.float64, copy=False)

            split = n_pairs // 2
            if split >= 2 and n_pairs - split >= 2:
                h_left = np.mean(pair_moments[:split], axis=0) / scale
                h_right = np.mean(pair_moments[split:], axis=0) / scale
                self._last_h_split_correlation = _vector_correlation(h_left, h_right)
                self._last_h_split_sign_agreement = float(
                    np.mean(np.signbit(h_left) == np.signbit(h_right))
                )
                split_scale = 0.5 * (
                    float(np.linalg.norm(h_left)) + float(np.linalg.norm(h_right))
                )
                self._last_h_split_relative_disagreement = float(
                    np.linalg.norm(h_left - h_right) / (split_scale + 1e-12)
                )

            previous = self._previous_diag_h_raw
            if previous is not None and previous.shape == h_raw.shape:
                self._last_h_temporal_correlation = _vector_correlation(previous, h_raw)
                self._last_h_temporal_sign_agreement = float(
                    np.mean(np.signbit(previous) == np.signbit(h_raw))
                )
            self._previous_diag_h_raw = h_raw.copy()
            return h_raw, n_pairs

        if self.curvature_mode == "directional":
            if direction is None:
                return None, 0
            u = np.asarray(direction, dtype=np.float64)
            u_norm = float(np.linalg.norm(u))
            if u_norm <= 1e-12 or not np.isfinite(u_norm):
                return None, 0
            u = u / u_norm
            proj = eps @ u
            h_scalar = np.mean(pair_signal * (proj * proj - 1.0))
            h_scalar /= 2.0 * sigma_sq + 1e-12
            return np.full(self.num_params, h_scalar, dtype=np.float64), n_pairs

        if self.curvature_mode == "global":
            d = eps.shape[1]
            h_scalar = np.mean(pair_signal * (np.sum(eps * eps, axis=1) - d))
            h_scalar /= 2.0 * sigma_sq * d + 1e-12
            return np.full(self.num_params, h_scalar, dtype=np.float64), n_pairs

        if self.curvature_mode == "block":
            h_raw = np.zeros(self.num_params, dtype=np.float64)
            for sl in self.block_slices:
                eps_block = eps[:, sl]
                d_block = eps_block.shape[1]
                h_block = np.mean(pair_signal * (np.sum(eps_block * eps_block, axis=1) - d_block))
                h_block /= 2.0 * sigma_sq * d_block + 1e-12
                h_raw[sl] = h_block
            return h_raw, n_pairs

        raise ValueError(f"unknown curvature_mode: {self.curvature_mode}")

    def _hessian_for_step(self) -> np.ndarray:
        if not self.bias_correct_curvature_ema or self.hessian_ema_count <= 0:
            return self.hessian_ema
        # Adam-style bias correction so early EMA values are not near zero. 
        correction = 1.0 - self.curvature_beta**self.hessian_ema_count
        if correction <= 1e-12:
            return self.hessian_ema
        return self.hessian_ema / correction

    def tell(
        self,
        params: np.ndarray,
        noise: np.ndarray,
        fitness: np.ndarray,
        ask_info: dict[str, Any] | None = None,
        center_fitness: float | None = None,
    ) -> tuple[np.ndarray, dict[str, Any]]:
        theta_t = np.asarray(params, dtype=np.float64)
        noise = np.asarray(noise, dtype=np.float64)
        batch_size = int(len(noise))
        if batch_size == 0:
            return theta_t.copy(), {"n_fresh": 0, "n_reused": 0}

        # Ensure tell() updates the same center that ask() used to generate this batch.
        if ask_info is not None and "ask_params" in ask_info:
            # The following check whether theta_t - np.asarray(ask_info["ask_params"]) <= atol + rtol * abs(np.asarray(ask_info["ask_params"]))
            if not np.allclose(theta_t, np.asarray(ask_info["ask_params"]), rtol=1e-7, atol=1e-9):
                raise ValueError("tell() params must match the params used by ask().")

        if ask_info is not None and "is_reused" in ask_info:
            is_reused = np.asarray(ask_info["is_reused"], dtype=bool)
        else:
            is_reused = np.zeros(batch_size, dtype=bool)
        if len(is_reused) != batch_size:
            raise ValueError(f"is_reused length must be {batch_size}, got {len(is_reused)}")

        n_reused = int(np.sum(is_reused))
        n_fresh = int(batch_size - n_reused)
        # fresh_mask is the array indicating whehter the sample is newly sampled or reused.
        fresh_mask = ~is_reused
        fitness_raw = self._compose_full_fitness(fitness, is_reused, ask_info, batch_size)

        if n_fresh > 0:
            self._add_fresh_to_buffer(theta_t, noise[fresh_mask], fitness_raw[fresh_mask])
        # Normalization is based on fresh samples, not reused samples when fresh samples exist.
        ref = fitness_raw[fresh_mask] if np.any(fresh_mask) else fitness_raw
        fit_mean = float(np.mean(ref))
        fit_std = float(np.std(ref) + 1e-8)
        f_standardized = (fitness_raw - fit_mean) / fit_std
        if self.curvature_fitness == "raw":
            f_for_curv = fitness_raw
        else:
            f_for_curv = f_standardized
        if self.rank_fitness:
            f_for_grad = centered_ranks(fitness_raw)
            gradient_transform = "rank_gradient"
        else:
            f_for_grad = f_standardized
            gradient_transform = "standardized_gradient"
        fitness_transform = f"{gradient_transform}_{self.curvature_fitness}_curvature"

        sigma_target = float(self.noise_std)
        sigma_old = np.full(batch_size, sigma_target, dtype=np.float64)
        # squared distance from the sample to the center that originally generated it.
        dist_old_sq = np.zeros(batch_size, dtype=np.float64)
        dist_old_sq[fresh_mask] = (sigma_target * sigma_target) * np.sum(
            noise[fresh_mask] * noise[fresh_mask],
            axis=1,
        ) # axis = 1 means summing across the column(the dimensionwise through the parameter)
        if n_reused > 0 and ask_info is not None:
            if ask_info.get("buffer_sigma_old") is not None:
                sigma_old[is_reused] = np.asarray(ask_info["buffer_sigma_old"], dtype=np.float64)
            if ask_info.get("buffer_dist_old_sq") is not None:
                dist_old_sq[is_reused] = np.asarray(ask_info["buffer_dist_old_sq"], dtype=np.float64)

        d = float(self.num_params)
        dist_new_sq = (sigma_target * sigma_target) * np.sum(noise * noise, axis=1)
        with np.errstate(divide="ignore", invalid="ignore"):
            log_ratio = d * np.log(sigma_old / sigma_target)
            log_ratio += dist_old_sq / (2.0 * sigma_old * sigma_old)
            log_ratio -= dist_new_sq / (2.0 * sigma_target * sigma_target)
        clip_mask = (log_ratio <= self._log_rmin) | (log_ratio >= self._log_rmax)
        log_ratio = np.clip(log_ratio, self._log_rmin, self._log_rmax)
        ratios = np.exp(log_ratio)
        # ratio_sum is there to normalize the unnormalized importance ratios into weights that sum to 1.
        # For reused samples, each ratio says: "how plausible is this old sample under the current search distribution compared with the distribution that originally generated it?" Normalizing by the sum turns those plausibilities into relative contributions across the whole batch.
        ratio_sum = float(np.sum(ratios))
        importance_ratio_fallback = False
        # The following condition is used to prevent some bad numerical instability
        if ratio_sum <= 0.0 or not np.isfinite(ratio_sum):
            importance_ratio_fallback = True
            # This is similar to the standard evolution strategy with the only different that the following includes some reused samples with uniform weights while for the standard evolution strategies, all the perturbations are freshly sampled and evaluated.
            weights = np.full(batch_size, 1.0 / batch_size, dtype=np.float64)
        else:
            weights = ratios / ratio_sum

        ess = float(1.0 / (np.sum(weights * weights) + 1e-12))
        ess_ratio = float(ess / batch_size)
        used_replay = n_reused > 0
        if ess_ratio < self.ess_min_ratio and n_fresh > 0:
            used_replay = False
            weights = np.zeros(batch_size, dtype=np.float64)
            # fresh_mask is a boolean array marking which rows in the batch are newly sampled in the current iteration.
            weights[fresh_mask] = 1.0 / max(1, n_fresh)
            ess = float(1.0 / (np.sum(weights * weights) + 1e-12))
            ess_ratio = float(ess / batch_size)

        weighted_f_mean = float(np.sum(weights * f_for_grad))
        advantages = f_for_grad - weighted_f_mean
        # Good samples with positive advantage push the parameters in the direction of their noise and bad samples with negative advantage push against their noise direction.
        grad = np.sum(weights[:, None] * advantages[:, None] * noise, axis=0)
        grad /= sigma_target + 1e-10
        # The following adds L2 regularization. It pulls parameters back toward zero, penalizing large parameter norms.
        if self.l2_coeff > 0.0:
            grad -= self.l2_coeff * theta_t

        # This code computes the size of the gradient vector using Euclidean norm.
        grad_norm_before_clip = float(np.linalg.norm(grad))
        if self.max_grad_norm > 0.0 and grad_norm_before_clip > self.max_grad_norm:
            grad = grad * (self.max_grad_norm / (grad_norm_before_clip + 1e-12))
        grad_norm = float(np.linalg.norm(grad))

        center_f_for_curv = None
        if center_fitness is not None:
            if self.curvature_fitness == "raw":
                center_f_for_curv = float(center_fitness)
            else:
                center_f_for_curv = (float(center_fitness) - fit_mean) / fit_std

        h_raw, n_hessian_pairs = None, 0
        if self.use_curvature:
            h_raw, n_hessian_pairs = self._estimate_fresh_curvature(
                noise=noise,
                f=f_for_curv,
                ask_info=ask_info,
                sigma=sigma_target,
                center_f_for_curv=center_f_for_curv,
                direction=grad,
            )
        if h_raw is not None:
            # ema is a smoothed running estimate of that curvature
            self.hessian_ema = self.curvature_beta * self.hessian_ema
            # self.curvature_beta controls smoothing
            self.hessian_ema += (1.0 - self.curvature_beta) * h_raw
            # count records how many curvature updates we have been accumulated.
            self.hessian_ema_count += 1
        # Gets the smoothed Hessian/curvature estimate.
        hessian_for_step = self._hessian_for_step()
        # alpha is the learning rate
        alpha = float(self.learning_rate)
        # lam is a global damping term that makes every step smaller and more stable
        lam = float(self.implicit_damping)
        curvature_coordinate_count = int(hessian_for_step.size)
        if self.use_curvature:
            # Only directions with negative curvature shrink the step. Positive directions do not add curvature damping.
            curvature_preclip = np.maximum(-hessian_for_step, 0.0)
        else:
            curvature_preclip = np.zeros_like(grad)
        curvature_clip_mask = (
            curvature_preclip > self.curvature_clip
            if self.use_curvature
            else np.zeros(curvature_preclip.shape, dtype=bool)
        )
        curvature_clip_count = int(np.count_nonzero(curvature_clip_mask))
        if curvature_clip_count:
            curvature_clip_excess = (
                curvature_preclip[curvature_clip_mask] - self.curvature_clip
            )
            curvature_clip_excess_mean = float(np.mean(curvature_clip_excess))
            curvature_clip_excess_max = float(np.max(curvature_clip_excess))
        else:
            curvature_clip_excess_mean = 0.0
            curvature_clip_excess_max = 0.0
        # Clip only after recording the strict pre-clip mask, so equality with
        # the cap is not reported as an intervention.
        curv = (
            np.clip(curvature_preclip, 0.0, self.curvature_clip)
            if self.use_curvature
            else curvature_preclip
        )
        if self.l2_coeff > 0.0 and self.curvature_step_mode == "dampen":
            curv = curv + self.l2_coeff
        # Preserve the legacy post-processing meaning of
        # ``curvature_active_frac`` while adding its exact count.
        curvature_active_mask = curv > 0.0
        curvature_active_count = int(np.count_nonzero(curvature_active_mask))

        linear_system_diagonal: np.ndarray | None = None
        multiplier_coordinate_count = int(grad.size)
        raw_step_multiplier = np.ones_like(grad)
        multiplier_floor_clip_mask = np.zeros(grad.shape, dtype=bool)
        multiplier_ceiling_clip_mask = np.zeros(grad.shape, dtype=bool)
        multiplier_clipping_diagnostics_exact = not (
            self.curvature_step_mode == "normalized" and self.use_curvature
        )
        if self.curvature_step_mode == "normalized" and self.use_curvature:
            base_denom = 1.0 + alpha * lam
            if self.l2_coeff > 0.0:
                base_denom += alpha * self.l2_coeff
            base_multiplier = float(np.clip(1.0 / max(base_denom, 1e-12), self.min_step_multiplier, 1.0))
            preconditioner = 1.0 / np.sqrt(1.0 + alpha * curv)
            preconditioner_rms = float(np.sqrt(np.mean(preconditioner * preconditioner)) + 1e-12)
            preconditioner = preconditioner / preconditioner_rms
            if self.min_step_multiplier > 0.0:
                preconditioner = np.clip(
                    preconditioner,
                    self.min_step_multiplier,
                    1.0 / max(self.min_step_multiplier, 1e-12),
                )
            multiplier = base_multiplier * preconditioner
            # This mode clips the normalized preconditioner rather than the
            # final step multiplier. The final-multiplier diagnostics below
            # therefore report no direct lower/upper intervention here.
            raw_step_multiplier = multiplier.copy()
        else:
            denom = 1.0 + alpha * lam + alpha * curv
            linear_system_diagonal = np.maximum(denom, 1e-12)
            raw_step_multiplier = 1.0 / linear_system_diagonal
            multiplier_floor_clip_mask = (
                raw_step_multiplier < self.min_step_multiplier
            )
            multiplier_ceiling_clip_mask = raw_step_multiplier > 1.0
            multiplier = np.clip(
                raw_step_multiplier, self.min_step_multiplier, 1.0
            )
        multiplier_floor_clip_count = int(
            np.count_nonzero(multiplier_floor_clip_mask)
        )
        if multiplier_floor_clip_count:
            multiplier_floor_clip_deficit = (
                self.min_step_multiplier
                - raw_step_multiplier[multiplier_floor_clip_mask]
            )
            multiplier_floor_clip_deficit_mean = float(
                np.mean(multiplier_floor_clip_deficit)
            )
            multiplier_floor_clip_deficit_max = float(
                np.max(multiplier_floor_clip_deficit)
            )
        else:
            multiplier_floor_clip_deficit_mean = 0.0
            multiplier_floor_clip_deficit_max = 0.0
        multiplier_ceiling_clip_count = int(
            np.count_nonzero(multiplier_ceiling_clip_mask)
        )
        if multiplier_ceiling_clip_count:
            multiplier_ceiling_clip_excess = (
                raw_step_multiplier[multiplier_ceiling_clip_mask] - 1.0
            )
            multiplier_ceiling_clip_excess_mean = float(
                np.mean(multiplier_ceiling_clip_excess)
            )
            multiplier_ceiling_clip_excess_max = float(
                np.max(multiplier_ceiling_clip_excess)
            )
        else:
            multiplier_ceiling_clip_excess_mean = 0.0
            multiplier_ceiling_clip_excess_max = 0.0
        step_pre_trust = alpha * multiplier * grad
        pre_trust_step_norm = float(np.linalg.norm(step_pre_trust))

        division_relative_residual: float | None = None
        applied_relative_residual: float | None = None
        linear_condition_estimate: float | None = None
        linear_min_abs_diagonal: float | None = None
        linear_max_abs_diagonal: float | None = None
        if linear_system_diagonal is not None:
            rhs = alpha * grad
            division_step = rhs / linear_system_diagonal
            rhs_scale = float(np.linalg.norm(rhs)) + 1e-12
            division_relative_residual = float(
                np.linalg.norm(linear_system_diagonal * division_step - rhs) / rhs_scale
            )
            applied_relative_residual = float(
                np.linalg.norm(linear_system_diagonal * step_pre_trust - rhs) / rhs_scale
            )
            abs_diagonal = np.abs(linear_system_diagonal)
            linear_min_abs_diagonal = float(np.min(abs_diagonal))
            linear_max_abs_diagonal = float(np.max(abs_diagonal))
            linear_condition_estimate = float(
                linear_max_abs_diagonal / max(linear_min_abs_diagonal, 1e-300)
            )

        no_curv_denom = 1.0 + alpha * lam
        if self.l2_coeff > 0.0:
            no_curv_denom += alpha * self.l2_coeff
        no_curv_multiplier = float(np.clip(1.0 / max(no_curv_denom, 1e-12), self.min_step_multiplier, 1.0))
        step_no_curv_pre_trust = alpha * no_curv_multiplier * grad
        no_curv_pre_trust_step_norm = float(np.linalg.norm(step_no_curv_pre_trust))

        trust_active = False
        trust_scale = 1.0
        step = step_pre_trust
        if (
            self.trust_radius is not None
            and pre_trust_step_norm > self.trust_radius
            and pre_trust_step_norm > 1e-12
        ):
            trust_active = True
            trust_scale = float(self.trust_radius / pre_trust_step_norm)
            step = step_pre_trust * trust_scale

        theta = theta_t + step
        if self.max_param_norm is not None:
            param_norm = float(np.linalg.norm(theta))
            if param_norm > self.max_param_norm and param_norm > 1e-12:
                theta = theta * (float(self.max_param_norm) / param_norm)
        applied_step_norm = float(np.linalg.norm(theta - theta_t))

        cos_den = pre_trust_step_norm * no_curv_pre_trust_step_norm + 1e-12
        cos_curv_vs_no_curv = float(np.dot(step_pre_trust, step_no_curv_pre_trust) / cos_den)

        self.iteration += 1
        self.eval_count += n_fresh
        self.current_params = theta.copy()
        # Keep exact coordinate histories out of the scalar info/JSON path.
        # Defensive properties expose read-only copies to the trainer.
        self._last_hessian_for_step_vector = np.asarray(
            hessian_for_step, dtype=np.float64
        ).copy()
        self._last_step_multiplier_vector = np.asarray(
            multiplier, dtype=np.float64
        ).copy()

        w_max = float(np.max(weights))
        w_min = float(np.min(weights))
        ratio_mean = float(np.mean(ratios))
        ratio_min = float(np.min(ratios))
        ratio_max = float(np.max(ratios))
        replay_weight_mass = float(np.sum(weights[is_reused])) if n_reused else 0.0
        fresh_weight_mass = float(np.sum(weights[fresh_mask])) if n_fresh else 0.0
        replay_ratio_mean = float(np.mean(ratios[is_reused])) if n_reused else 0.0
        replay_ratio_min = float(np.min(ratios[is_reused])) if n_reused else 0.0
        replay_ratio_max = float(np.max(ratios[is_reused])) if n_reused else 0.0
        fresh_ratio_mean = float(np.mean(ratios[fresh_mask])) if n_fresh else 0.0
        replay_weight_mean = float(np.mean(weights[is_reused])) if n_reused else 0.0
        replay_weight_max = float(np.max(weights[is_reused])) if n_reused else 0.0
        fresh_weight_mean = float(np.mean(weights[fresh_mask])) if n_fresh else 0.0
        fresh_weight_max = float(np.max(weights[fresh_mask])) if n_fresh else 0.0
        replay_clip_frac = float(np.mean(clip_mask[is_reused])) if n_reused else 0.0
        fresh_clip_frac = float(np.mean(clip_mask[fresh_mask])) if n_fresh else 0.0
        multiplier_mean = float(np.mean(multiplier))
        multiplier_std = float(np.std(multiplier))
        step_norm_ratio = float(applied_step_norm / (no_curv_pre_trust_step_norm + 1e-12))
        info: dict[str, Any] = {
            "grad_norm": grad_norm,
            "grad_norm_before_clip": grad_norm_before_clip,
            "param_norm": float(np.linalg.norm(theta)),
            "param_change": applied_step_norm,
            "step_norm": applied_step_norm,
            "pre_trust_step_norm": pre_trust_step_norm,
            "no_curv_pre_trust_step_norm": no_curv_pre_trust_step_norm,
            "trust_active": bool(trust_active),
            "trust_scale": trust_scale,
            "curv_norm_shrink": float(pre_trust_step_norm / (no_curv_pre_trust_step_norm + 1e-12)),
            "cos_curv_vs_no_curv_pre_trust": cos_curv_vs_no_curv,
            "mean_fitness": float(np.mean(fitness_raw)),
            "std_fitness": float(np.std(fitness_raw)),
            "max_fitness": float(np.max(fitness_raw)),
            "min_fitness": float(np.min(fitness_raw)),
            "iteration": int(self.iteration),
            "eval_count": int(self.eval_count),
            "n_reused": int(n_reused),
            "n_fresh": int(n_fresh),
            "buffer_size": int(len(self.sample_buffer)),
            "ess": ess,
            "ess_ratio": ess_ratio,
            "ess_normalized": ess_ratio,
            "clip_frac": float(np.mean(clip_mask)),
            "clip_fraction": float(np.mean(clip_mask)),
            "w_max": w_max,
            "w_min": w_min,
            "max_weight_ratio": float(w_max * batch_size),
            "mean_importance_weight": ratio_mean,
            "max_importance_weight": ratio_max,
            "importance_weight_mean": ratio_mean,
            "importance_weight_min": ratio_min,
            "importance_weight_max": ratio_max,
            "used_replay": bool(used_replay),
            "importance_ratio_fallback": bool(importance_ratio_fallback),
            "replay_weight_mass": replay_weight_mass,
            "fresh_weight_mass": fresh_weight_mass,
            "replay_ratio_mean": replay_ratio_mean,
            "replay_ratio_min": replay_ratio_min,
            "replay_ratio_max": replay_ratio_max,
            "fresh_ratio_mean": fresh_ratio_mean,
            "replay_weight_mean": replay_weight_mean,
            "replay_weight_max": replay_weight_max,
            "fresh_weight_mean": fresh_weight_mean,
            "fresh_weight_max": fresh_weight_max,
            "replay_clip_frac": replay_clip_frac,
            "fresh_clip_frac": fresh_clip_frac,
            "hessian_pairs": int(n_hessian_pairs),
            "curv_mean": float(np.mean(curv)),
            "curv_max": float(np.max(curv)),
            "curv_min": float(np.min(curv)),
            "curvature_coordinate_count": curvature_coordinate_count,
            "curvature_active_count": curvature_active_count,
            "curvature_active_frac": float(
                curvature_active_count / curvature_coordinate_count
            ),
            "curvature_preclip_mean": float(np.mean(curvature_preclip)),
            "curvature_preclip_max": float(np.max(curvature_preclip)),
            "curvature_clip_count": curvature_clip_count,
            "curvature_clip_frac": float(
                curvature_clip_count / curvature_coordinate_count
            ),
            "curvature_clip_active": bool(curvature_clip_count > 0),
            "curvature_clip_excess_mean": curvature_clip_excess_mean,
            "curvature_clip_excess_max": curvature_clip_excess_max,
            "explicit_step_norm": no_curv_pre_trust_step_norm,
            "step_norm_ratio": step_norm_ratio,
            "hessian_shrinkage_median": float(np.median(multiplier)),
            "hessian_shrinkage_p90": float(np.percentile(multiplier, 90.0)),
            "hessian_shrinkage_max": float(np.max(multiplier)),
            "lambda": lam,
            "sigma": sigma_target,
            "learning_rate": alpha,
            "reuse_fraction": float(self.reuse_fraction),
            "step_multiplier_mean": multiplier_mean,
            "step_multiplier_std": multiplier_std,
            "step_multiplier_cv": float(multiplier_std / (multiplier_mean + 1e-12)),
            "step_multiplier_min": float(np.min(multiplier)),
            "step_multiplier_max": float(np.max(multiplier)),
            "multiplier_coordinate_count": multiplier_coordinate_count,
            "raw_step_multiplier_min": float(np.min(raw_step_multiplier)),
            "raw_step_multiplier_max": float(np.max(raw_step_multiplier)),
            "multiplier_clipping_diagnostics_exact": bool(
                multiplier_clipping_diagnostics_exact
            ),
            "multiplier_floor_clip_count": multiplier_floor_clip_count,
            "multiplier_floor_clip_frac": float(
                multiplier_floor_clip_count / multiplier_coordinate_count
            ),
            "multiplier_floor_clip_active": bool(
                multiplier_floor_clip_count > 0
            ),
            "multiplier_floor_clip_deficit_mean": (
                multiplier_floor_clip_deficit_mean
            ),
            "multiplier_floor_clip_deficit_max": (
                multiplier_floor_clip_deficit_max
            ),
            "multiplier_ceiling_clip_count": multiplier_ceiling_clip_count,
            "multiplier_ceiling_clip_frac": float(
                multiplier_ceiling_clip_count / multiplier_coordinate_count
            ),
            "multiplier_ceiling_clip_active": bool(
                multiplier_ceiling_clip_count > 0
            ),
            "multiplier_ceiling_clip_excess_mean": (
                multiplier_ceiling_clip_excess_mean
            ),
            "multiplier_ceiling_clip_excess_max": (
                multiplier_ceiling_clip_excess_max
            ),
            # Legacy at-floor occupancy includes coordinates that naturally
            # equal the floor; the *_clip_* fields above count interventions.
            "multiplier_floor_frac": float(np.mean(multiplier <= self.min_step_multiplier + 1e-12)),
            "fitness_transform": fitness_transform,
            "curvature_baseline": self._last_curvature_baseline_mode,
            "curvature_fitness": self.curvature_fitness,
            "curvature_return_std": fit_std,
            "curvature_mode": self.curvature_mode,
            "curvature_step_mode": self.curvature_step_mode,
            "hessian_ema_count": int(self.hessian_ema_count),
            "h_split_correlation": self._last_h_split_correlation,
            "h_split_sign_agreement": self._last_h_split_sign_agreement,
            "h_split_relative_disagreement": self._last_h_split_relative_disagreement,
            "h_temporal_correlation": self._last_h_temporal_correlation,
            "h_temporal_sign_agreement": self._last_h_temporal_sign_agreement,
            "division_relative_residual": division_relative_residual,
            "applied_relative_residual": applied_relative_residual,
            "linear_condition_estimate": linear_condition_estimate,
            "linear_min_abs_diagonal": linear_min_abs_diagonal,
            "linear_max_abs_diagonal": linear_max_abs_diagonal,
            "converged": bool(
                division_relative_residual is None
                or (
                    np.isfinite(division_relative_residual)
                    and division_relative_residual <= 1e-10
                )
            ),
            "residual": (
                0.0 if division_relative_residual is None else division_relative_residual
            ),
        }
        if h_raw is not None:
            info.update(
                {
                    "h_raw_mean": float(np.mean(h_raw)),
                    "h_raw_std": float(np.std(h_raw)),
                    "h_raw_min": float(np.min(h_raw)),
                    "h_raw_max": float(np.max(h_raw)),
                    "h_ema_mean": float(np.mean(self.hessian_ema)),
                    "h_ema_min": float(np.min(self.hessian_ema)),
                    "h_ema_max": float(np.max(self.hessian_ema)),
                    "h_step_mean": float(np.mean(hessian_for_step)),
                    "h_step_min": float(np.min(hessian_for_step)),
                    "h_step_max": float(np.max(hessian_for_step)),
                }
            )
        return theta.astype(np.float64, copy=True), info
