"""DIIWES optimizer.

Design choices kept explicit:
  - rank-shaped fitness is used only for the ES gradient;
  - Stein curvature uses raw fitness standardized on the fresh population;
  - no-center curvature uses a leave-one-out pair baseline;
  - curvature EMA is bias-corrected before forming the step denominator;
  - trust-radius clipping is part of the DIIWES update.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Sequence

import numpy as np

from .standard_es import StandardES, centered_ranks


@dataclass
class BufferEntry:
    """A replay-buffer sample generated by a previous search distribution."""

    w: np.ndarray
    behavior_mu: np.ndarray
    sigma: float
    dist_old_sq: float
    fitness: float
    iteration: int


class DIIWES(StandardES):
    """Semi-implicit ES with rank gradients and raw-fitness Stein curvature."""

    def __init__(
        self,
        num_params: int,
        population_size: int = 200,
        learning_rate: float = 0.02,
        noise_std: float = 0.02,
        l2_coeff: float = 0.0,
        buffer_size: int = 1024,
        reuse_fraction: float = 0.2,
        min_importance_weight: float = 1e-3,
        max_importance_weight: float = 10.0,
        implicit_damping: float = 0.1,
        antithetic: bool = True,
        rank_fitness: bool = True,
        max_grad_norm: float = 0.0,
        max_sample_age: int = 3,
        buffer_sampling: str = "random",
        elite_quantile: float = 0.25,
        max_param_norm: float | None = None,
        seed: int | None = None,
        *,
        use_curvature: bool = True,
        curvature_mode: str = "diag",
        curvature_beta: float = 0.99,
        curvature_clip: float = 1e3,
        min_step_multiplier: float = 0.05,
        trust_radius: float | None = None,
        ess_min_ratio: float = 0.2,
        block_slices: Sequence[slice | Sequence[int]] | None = None,
        use_leave_one_out_curvature_baseline: bool = True,
        bias_correct_curvature_ema: bool = True,
    ) -> None:
        super().__init__(
            num_params=num_params,
            population_size=population_size,
            learning_rate=learning_rate,
            noise_std=noise_std,
            l2_coeff=l2_coeff,
            antithetic=antithetic,
            rank_fitness=rank_fitness,
            max_grad_norm=max_grad_norm,
            max_param_norm=max_param_norm,
            seed=seed,
        )
        if not (0.0 <= reuse_fraction <= 1.0):
            raise ValueError("reuse_fraction must be in [0, 1]")
        if min_importance_weight <= 0.0 or max_importance_weight <= 0.0:
            raise ValueError("importance weight bounds must be positive")
        if min_importance_weight > max_importance_weight:
            raise ValueError("min_importance_weight must be <= max_importance_weight")
        if not (0.0 <= curvature_beta < 1.0):
            raise ValueError("curvature_beta must be in [0, 1)")
        if not (0.0 <= min_step_multiplier <= 1.0):
            raise ValueError("min_step_multiplier must be in [0, 1]")
        if trust_radius is not None and trust_radius <= 0.0:
            raise ValueError("trust_radius must be positive when provided")
        if not (0.0 <= ess_min_ratio <= 1.0):
            raise ValueError("ess_min_ratio must be in [0, 1]")

        curvature_mode = str(curvature_mode).lower()
        if curvature_mode not in {"global", "block", "diag"}:
            raise ValueError("curvature_mode must be one of global, block, diag")

        self.buffer_size = int(buffer_size)
        self.reuse_fraction = float(reuse_fraction)
        self.min_importance_weight = float(min_importance_weight)
        self.max_importance_weight = float(max_importance_weight)
        self.implicit_damping = float(implicit_damping)
        self.max_sample_age = int(max_sample_age)
        self.buffer_sampling = str(buffer_sampling).lower()
        self.elite_quantile = float(elite_quantile)
        self.use_curvature = bool(use_curvature)
        self.curvature_mode = curvature_mode
        self.curvature_beta = float(curvature_beta)
        self.curvature_clip = float(curvature_clip)
        self.min_step_multiplier = float(min_step_multiplier)
        self.trust_radius = None if trust_radius is None else float(trust_radius)
        self.ess_min_ratio = float(ess_min_ratio)
        self.use_leave_one_out_curvature_baseline = bool(use_leave_one_out_curvature_baseline)
        self.bias_correct_curvature_ema = bool(bias_correct_curvature_ema)
        self.block_slices = self._normalize_block_slices(block_slices)

        self._log_rmin = float(np.log(self.min_importance_weight))
        self._log_rmax = float(np.log(self.max_importance_weight))
        self.sample_buffer: list[BufferEntry] = []
        self.n_reuse_target = int(np.floor(self.population_size * self.reuse_fraction))
        self.hessian_ema = np.zeros(self.num_params, dtype=np.float64)
        self.hessian_ema_count = 0
        self._last_curvature_baseline_mode = "none"

    def _normalize_block_slices(
        self,
        block_slices: Sequence[slice | Sequence[int]] | None,
    ) -> list[slice]:
        if block_slices is None:
            return [slice(0, self.num_params)]

        normalized: list[slice] = []
        coverage = np.zeros(self.num_params, dtype=np.int8)
        for item in block_slices:
            if isinstance(item, slice):
                start = 0 if item.start is None else int(item.start)
                stop = self.num_params if item.stop is None else int(item.stop)
            else:
                if len(item) != 2:
                    raise ValueError("block_slices entries must be slices or [start, stop] pairs")
                start, stop = int(item[0]), int(item[1])
            if start < 0 or stop > self.num_params or start >= stop:
                raise ValueError(f"invalid block slice [{start}, {stop}) for d={self.num_params}")
            coverage[start:stop] += 1
            normalized.append(slice(start, stop))

        if np.any(coverage != 1):
            raise ValueError("block_slices must form a non-overlapping full partition")
        return normalized

    def _valid_buffer_indices(self) -> list[int]:
        return [
            i
            for i, entry in enumerate(self.sample_buffer)
            if self.iteration - entry.iteration <= self.max_sample_age
        ]

    def _select_from_buffer(self, theta_current: np.ndarray, n_select: int) -> list[int]:
        valid = self._valid_buffer_indices()
        if n_select <= 0 or not valid:
            return []
        n_select = min(int(n_select), len(valid))

        if self.buffer_sampling == "random":
            return self.rng.choice(valid, size=n_select, replace=False).tolist()

        distances = np.asarray(
            [np.sum((self.sample_buffer[idx].w - theta_current) ** 2) for idx in valid],
            dtype=np.float64,
        )
        if self.buffer_sampling == "distance":
            order = np.argsort(distances)
            return [valid[i] for i in order[:n_select]]

        if self.buffer_sampling == "elite_distance":
            fitness = np.asarray([self.sample_buffer[idx].fitness for idx in valid], dtype=np.float64)
            quantile = np.clip(self.elite_quantile, 0.0, 1.0)
            threshold = np.quantile(fitness, 1.0 - quantile) if quantile > 0.0 else np.inf
            elite_local = np.where(fitness >= threshold)[0]
            if len(elite_local) == 0:
                elite_local = np.arange(len(valid))
            elite_order = elite_local[np.argsort(distances[elite_local])]
            return [valid[i] for i in elite_order[:n_select]]

        raise ValueError(f"unknown buffer_sampling mode: {self.buffer_sampling}")

    def _add_fresh_to_buffer(self, theta_center: np.ndarray, noise: np.ndarray, fitness: np.ndarray) -> None:
        if len(noise) == 0 or self.buffer_size <= 0:
            return
        sigma = float(self.noise_std)
        dist_old_sq = (sigma * sigma) * np.sum(noise * noise, axis=1)
        for i in range(len(noise)):
            self.sample_buffer.append(
                BufferEntry(
                    w=(theta_center + sigma * noise[i]).astype(np.float64, copy=True),
                    behavior_mu=theta_center.astype(np.float64, copy=True),
                    sigma=sigma,
                    dist_old_sq=float(dist_old_sq[i]),
                    fitness=float(fitness[i]),
                    iteration=int(self.iteration),
                )
            )
            if len(self.sample_buffer) > self.buffer_size:
                self.sample_buffer.pop(0)

    def _sample_fresh_noise_with_pairs(
        self,
        n_samples: int,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        if n_samples <= 0:
            empty_noise = np.empty((0, self.num_params), dtype=np.float64)
            empty_idx = np.asarray([], dtype=int)
            return empty_noise, empty_idx, empty_idx

        if not self.antithetic or n_samples == 1:
            return self.rng.randn(n_samples, self.num_params), np.asarray([], dtype=int), np.asarray([], dtype=int)

        half = n_samples // 2
        noise_half = self.rng.randn(half, self.num_params)
        noise = np.concatenate([noise_half, -noise_half], axis=0)
        plus = np.arange(half, dtype=int)
        minus = np.arange(half, 2 * half, dtype=int)
        if n_samples % 2 == 1:
            noise = np.concatenate([noise, self.rng.randn(1, self.num_params)], axis=0)
        return noise.astype(np.float64, copy=False), plus, minus

    def ask(self) -> tuple[np.ndarray, dict[str, Any]]:
        selected = self._select_from_buffer(self.current_params, self.n_reuse_target)

        noise_reused = []
        fitness_reused = []
        sigma_old = []
        dist_old_sq = []
        behavior_mu = []
        for idx in selected:
            entry = self.sample_buffer[idx]
            noise_reused.append((entry.w.astype(np.float64) - self.current_params) / self.noise_std)
            fitness_reused.append(entry.fitness)
            sigma_old.append(entry.sigma)
            dist_old_sq.append(entry.dist_old_sq)
            behavior_mu.append(entry.behavior_mu)

        n_reused = len(noise_reused)
        n_fresh_needed = self.population_size - n_reused
        noise_fresh, plus_local, minus_local = self._sample_fresh_noise_with_pairs(n_fresh_needed)

        if n_reused:
            noise_all = np.concatenate([np.asarray(noise_reused, dtype=np.float64), noise_fresh], axis=0)
            is_reused = np.concatenate(
                [np.ones(n_reused, dtype=bool), np.zeros(len(noise_fresh), dtype=bool)],
                axis=0,
            )
        else:
            noise_all = noise_fresh
            is_reused = np.zeros(len(noise_fresh), dtype=bool)

        fresh_offset = n_reused
        return noise_all, {
            "ask_params": self.current_params.copy(),
            "n_fresh": int(len(noise_fresh)),
            "n_reused": int(n_reused),
            "is_reused": is_reused,
            "buffer_fitness": np.asarray(fitness_reused, dtype=np.float64) if n_reused else None,
            "buffer_sigma_old": np.asarray(sigma_old, dtype=np.float64) if n_reused else None,
            "buffer_dist_old_sq": np.asarray(dist_old_sq, dtype=np.float64) if n_reused else None,
            "buffer_behavior_mu": np.asarray(behavior_mu, dtype=np.float64) if n_reused else None,
            "selected_indices": selected,
            "fresh_pair_plus": fresh_offset + plus_local,
            "fresh_pair_minus": fresh_offset + minus_local,
        }

    def _compose_full_fitness(
        self,
        fitness: np.ndarray,
        is_reused: np.ndarray,
        ask_info: dict[str, Any] | None,
        batch_size: int,
    ) -> np.ndarray:
        fit = np.asarray(fitness, dtype=np.float64)
        n_reused = int(np.sum(is_reused))
        n_fresh = int(batch_size - n_reused)
        if len(fit) == batch_size:
            full = fit.copy()
            if n_reused and ask_info is not None and ask_info.get("buffer_fitness") is not None:
                full[is_reused] = np.asarray(ask_info["buffer_fitness"], dtype=np.float64)
            return full
        if len(fit) == n_fresh:
            if n_reused and (ask_info is None or ask_info.get("buffer_fitness") is None):
                raise ValueError("fresh-only fitness was provided but buffer_fitness is missing")
            full = np.empty(batch_size, dtype=np.float64)
            full[~is_reused] = fit
            if n_reused:
                full[is_reused] = np.asarray(ask_info["buffer_fitness"], dtype=np.float64)
            return full
        raise ValueError(f"fitness length must be {batch_size} or {n_fresh}, got {len(fit)}")

    def _estimate_fresh_curvature(
        self,
        noise: np.ndarray,
        f: np.ndarray,
        ask_info: dict[str, Any] | None,
        sigma: float,
        center_f_norm: float | None = None,
    ) -> tuple[np.ndarray | None, int]:
        if ask_info is None:
            return None, 0
        plus = np.asarray(ask_info.get("fresh_pair_plus", []), dtype=int)
        minus = np.asarray(ask_info.get("fresh_pair_minus", []), dtype=int)
        if len(plus) == 0 or len(minus) == 0:
            return None, 0

        n_pairs = min(len(plus), len(minus))
        plus = plus[:n_pairs]
        minus = minus[:n_pairs]
        eps = np.asarray(noise[plus], dtype=np.float64)
        s_pair = np.asarray(f[plus] + f[minus], dtype=np.float64)

        if center_f_norm is not None:
            pair_signal = s_pair - 2.0 * float(center_f_norm)
            baseline_mode = "center"
        elif self.use_leave_one_out_curvature_baseline and n_pairs > 1:
            loo_mean = (float(np.sum(s_pair)) - s_pair) / float(n_pairs - 1)
            pair_signal = s_pair - loo_mean
            baseline_mode = "leave_one_out"
        elif self.use_leave_one_out_curvature_baseline:
            pair_signal = s_pair
            baseline_mode = "single_pair_zero_baseline"
        else:
            baseline = float(0.5 * np.mean(s_pair))
            pair_signal = s_pair - 2.0 * baseline
            baseline_mode = "same_sample_mean"
        self._last_curvature_baseline_mode = baseline_mode

        sigma_sq = float(sigma) * float(sigma)
        if self.curvature_mode == "diag":
            h_raw = np.mean(pair_signal[:, None] * (eps * eps - 1.0), axis=0)
            h_raw /= 2.0 * sigma_sq + 1e-12
            return h_raw.astype(np.float64), n_pairs

        if self.curvature_mode == "global":
            d = eps.shape[1]
            h_scalar = np.mean(pair_signal * (np.sum(eps * eps, axis=1) - d))
            h_scalar /= 2.0 * sigma_sq * d + 1e-12
            return np.full(self.num_params, h_scalar, dtype=np.float64), n_pairs

        if self.curvature_mode == "block":
            h_raw = np.zeros(self.num_params, dtype=np.float64)
            for sl in self.block_slices:
                eps_block = eps[:, sl]
                d_block = eps_block.shape[1]
                h_block = np.mean(pair_signal * (np.sum(eps_block * eps_block, axis=1) - d_block))
                h_block /= 2.0 * sigma_sq * d_block + 1e-12
                h_raw[sl] = h_block
            return h_raw, n_pairs

        raise ValueError(f"unknown curvature_mode: {self.curvature_mode}")

    def _hessian_for_step(self) -> np.ndarray:
        if not self.bias_correct_curvature_ema or self.hessian_ema_count <= 0:
            return self.hessian_ema
        correction = 1.0 - self.curvature_beta**self.hessian_ema_count
        if correction <= 1e-12:
            return self.hessian_ema
        return self.hessian_ema / correction

    def tell(
        self,
        params: np.ndarray,
        noise: np.ndarray,
        fitness: np.ndarray,
        ask_info: dict[str, Any] | None = None,
        center_fitness: float | None = None,
    ) -> tuple[np.ndarray, dict[str, Any]]:
        theta_t = np.asarray(params, dtype=np.float64)
        noise = np.asarray(noise, dtype=np.float64)
        batch_size = int(len(noise))
        if batch_size == 0:
            return theta_t.copy(), {"n_fresh": 0, "n_reused": 0}

        if ask_info is not None and "ask_params" in ask_info:
            if not np.allclose(theta_t, np.asarray(ask_info["ask_params"]), rtol=1e-7, atol=1e-9):
                raise ValueError("tell() params must match the params used by ask().")

        if ask_info is not None and "is_reused" in ask_info:
            is_reused = np.asarray(ask_info["is_reused"], dtype=bool)
        else:
            is_reused = np.zeros(batch_size, dtype=bool)
        if len(is_reused) != batch_size:
            raise ValueError(f"is_reused length must be {batch_size}, got {len(is_reused)}")

        n_reused = int(np.sum(is_reused))
        n_fresh = int(batch_size - n_reused)
        fresh_mask = ~is_reused
        fitness_raw = self._compose_full_fitness(fitness, is_reused, ask_info, batch_size)

        if n_fresh > 0:
            self._add_fresh_to_buffer(theta_t, noise[fresh_mask], fitness_raw[fresh_mask])

        ref = fitness_raw[fresh_mask] if np.any(fresh_mask) else fitness_raw
        fit_mean = float(np.mean(ref))
        fit_std = float(np.std(ref) + 1e-8)
        f_for_curv = (fitness_raw - fit_mean) / fit_std
        if self.rank_fitness:
            f_for_grad = centered_ranks(fitness_raw)
            fitness_transform = "rank_gradient_raw_curvature"
        else:
            f_for_grad = f_for_curv
            fitness_transform = "standardized_gradient_raw_curvature"

        sigma_target = float(self.noise_std)
        sigma_old = np.full(batch_size, sigma_target, dtype=np.float64)
        dist_old_sq = np.zeros(batch_size, dtype=np.float64)
        dist_old_sq[fresh_mask] = (sigma_target * sigma_target) * np.sum(
            noise[fresh_mask] * noise[fresh_mask],
            axis=1,
        )
        if n_reused > 0 and ask_info is not None:
            if ask_info.get("buffer_sigma_old") is not None:
                sigma_old[is_reused] = np.asarray(ask_info["buffer_sigma_old"], dtype=np.float64)
            if ask_info.get("buffer_dist_old_sq") is not None:
                dist_old_sq[is_reused] = np.asarray(ask_info["buffer_dist_old_sq"], dtype=np.float64)

        d = float(self.num_params)
        dist_new_sq = (sigma_target * sigma_target) * np.sum(noise * noise, axis=1)
        with np.errstate(divide="ignore", invalid="ignore"):
            log_ratio = d * np.log(sigma_old / sigma_target)
            log_ratio += dist_old_sq / (2.0 * sigma_old * sigma_old)
            log_ratio -= dist_new_sq / (2.0 * sigma_target * sigma_target)
        clip_mask = (log_ratio <= self._log_rmin) | (log_ratio >= self._log_rmax)
        log_ratio = np.clip(log_ratio, self._log_rmin, self._log_rmax)
        ratios = np.exp(log_ratio)
        ratio_sum = float(np.sum(ratios))
        if ratio_sum <= 0.0 or not np.isfinite(ratio_sum):
            weights = np.full(batch_size, 1.0 / batch_size, dtype=np.float64)
        else:
            weights = ratios / ratio_sum

        ess = float(1.0 / (np.sum(weights * weights) + 1e-12))
        ess_ratio = float(ess / batch_size)
        used_replay = True
        if ess_ratio < self.ess_min_ratio and n_fresh > 0:
            used_replay = False
            weights = np.zeros(batch_size, dtype=np.float64)
            weights[fresh_mask] = 1.0 / max(1, n_fresh)
            ess = float(1.0 / (np.sum(weights * weights) + 1e-12))
            ess_ratio = float(ess / batch_size)

        weighted_f_mean = float(np.sum(weights * f_for_grad))
        advantages = f_for_grad - weighted_f_mean
        grad = np.sum(weights[:, None] * advantages[:, None] * noise, axis=0)
        grad /= sigma_target + 1e-10
        if self.l2_coeff > 0.0:
            grad -= self.l2_coeff * theta_t

        grad_norm_before_clip = float(np.linalg.norm(grad))
        if self.max_grad_norm > 0.0 and grad_norm_before_clip > self.max_grad_norm:
            grad = grad * (self.max_grad_norm / (grad_norm_before_clip + 1e-12))
        grad_norm = float(np.linalg.norm(grad))

        center_f_norm = None
        if center_fitness is not None:
            center_f_norm = (float(center_fitness) - fit_mean) / fit_std

        h_raw, n_hessian_pairs = None, 0
        if self.use_curvature:
            h_raw, n_hessian_pairs = self._estimate_fresh_curvature(
                noise=noise,
                f=f_for_curv,
                ask_info=ask_info,
                sigma=sigma_target,
                center_f_norm=center_f_norm,
            )
        if h_raw is not None:
            self.hessian_ema = self.curvature_beta * self.hessian_ema
            self.hessian_ema += (1.0 - self.curvature_beta) * h_raw
            self.hessian_ema_count += 1

        hessian_for_step = self._hessian_for_step()
        alpha = float(self.learning_rate)
        lam = float(self.implicit_damping)
        if self.use_curvature:
            curv = np.maximum(-hessian_for_step, 0.0)
            curv = np.clip(curv, 0.0, self.curvature_clip)
        else:
            curv = np.zeros_like(grad)
        if self.l2_coeff > 0.0:
            curv = curv + self.l2_coeff

        denom = 1.0 + alpha * lam + alpha * curv
        multiplier = 1.0 / np.maximum(denom, 1e-12)
        multiplier = np.clip(multiplier, self.min_step_multiplier, 1.0)
        step_pre_trust = alpha * multiplier * grad
        pre_trust_step_norm = float(np.linalg.norm(step_pre_trust))

        no_curv_denom = 1.0 + alpha * lam
        if self.l2_coeff > 0.0:
            no_curv_denom += alpha * self.l2_coeff
        no_curv_multiplier = float(np.clip(1.0 / max(no_curv_denom, 1e-12), self.min_step_multiplier, 1.0))
        step_no_curv_pre_trust = alpha * no_curv_multiplier * grad
        no_curv_pre_trust_step_norm = float(np.linalg.norm(step_no_curv_pre_trust))

        trust_active = False
        trust_scale = 1.0
        step = step_pre_trust
        if (
            self.trust_radius is not None
            and pre_trust_step_norm > self.trust_radius
            and pre_trust_step_norm > 1e-12
        ):
            trust_active = True
            trust_scale = float(self.trust_radius / pre_trust_step_norm)
            step = step_pre_trust * trust_scale

        theta = theta_t + step
        if self.max_param_norm is not None:
            param_norm = float(np.linalg.norm(theta))
            if param_norm > self.max_param_norm and param_norm > 1e-12:
                theta = theta * (float(self.max_param_norm) / param_norm)
        applied_step_norm = float(np.linalg.norm(theta - theta_t))

        cos_den = pre_trust_step_norm * no_curv_pre_trust_step_norm + 1e-12
        cos_curv_vs_no_curv = float(np.dot(step_pre_trust, step_no_curv_pre_trust) / cos_den)

        self.iteration += 1
        self.eval_count += n_fresh
        self.current_params = theta.copy()

        w_max = float(np.max(weights))
        w_min = float(np.min(weights))
        multiplier_mean = float(np.mean(multiplier))
        multiplier_std = float(np.std(multiplier))
        info: dict[str, Any] = {
            "grad_norm": grad_norm,
            "grad_norm_before_clip": grad_norm_before_clip,
            "param_norm": float(np.linalg.norm(theta)),
            "param_change": applied_step_norm,
            "step_norm": applied_step_norm,
            "pre_trust_step_norm": pre_trust_step_norm,
            "no_curv_pre_trust_step_norm": no_curv_pre_trust_step_norm,
            "trust_active": bool(trust_active),
            "trust_scale": trust_scale,
            "curv_norm_shrink": float(pre_trust_step_norm / (no_curv_pre_trust_step_norm + 1e-12)),
            "cos_curv_vs_no_curv_pre_trust": cos_curv_vs_no_curv,
            "mean_fitness": float(np.mean(fitness_raw)),
            "std_fitness": float(np.std(fitness_raw)),
            "max_fitness": float(np.max(fitness_raw)),
            "min_fitness": float(np.min(fitness_raw)),
            "iteration": int(self.iteration),
            "eval_count": int(self.eval_count),
            "n_reused": int(n_reused),
            "n_fresh": int(n_fresh),
            "buffer_size": int(len(self.sample_buffer)),
            "ess": ess,
            "ess_ratio": ess_ratio,
            "clip_frac": float(np.mean(clip_mask)),
            "w_max": w_max,
            "w_min": w_min,
            "max_weight_ratio": float(w_max * batch_size),
            "used_replay": bool(used_replay),
            "hessian_pairs": int(n_hessian_pairs),
            "curv_mean": float(np.mean(curv)),
            "curv_max": float(np.max(curv)),
            "curv_min": float(np.min(curv)),
            "curvature_active_frac": float(np.mean(curv > 0.0)),
            "step_multiplier_mean": multiplier_mean,
            "step_multiplier_std": multiplier_std,
            "step_multiplier_cv": float(multiplier_std / (multiplier_mean + 1e-12)),
            "step_multiplier_min": float(np.min(multiplier)),
            "step_multiplier_max": float(np.max(multiplier)),
            "multiplier_floor_frac": float(np.mean(multiplier <= self.min_step_multiplier + 1e-12)),
            "fitness_transform": fitness_transform,
            "curvature_baseline": self._last_curvature_baseline_mode,
            "hessian_ema_count": int(self.hessian_ema_count),
            "converged": True,
            "residual": 0.0,
        }
        if h_raw is not None:
            info.update(
                {
                    "h_raw_mean": float(np.mean(h_raw)),
                    "h_raw_std": float(np.std(h_raw)),
                    "h_raw_min": float(np.min(h_raw)),
                    "h_raw_max": float(np.max(h_raw)),
                    "h_ema_mean": float(np.mean(self.hessian_ema)),
                    "h_ema_min": float(np.min(self.hessian_ema)),
                    "h_ema_max": float(np.max(self.hessian_ema)),
                    "h_step_mean": float(np.mean(hessian_for_step)),
                    "h_step_min": float(np.min(hessian_for_step)),
                    "h_step_max": float(np.max(hessian_for_step)),
                }
            )
        return theta.astype(np.float64, copy=True), info
